Restore commented build steps

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -17,7 +17,6 @@ env:
   IS_PUBLIC: NO
 
 jobs:
-  # TODO: tauri exclude dmg?
   build-client:
     name: Build client
     permissions:
@@ -41,7 +40,6 @@ jobs:
             tauri-target: "x86_64-pc-windows-msvc"
     runs-on: ${{ matrix.platform-name }}
     env:
-      RELEASE_VERSION: ${{ github.ref_name }}
       TAURI_OUTPUT: ./src-tauri/target/${{ matrix.tauri-target }}/release/${{ matrix.tauri-path }}
       TAURI_BUILD_COMMAND: npm run tauri-pack -- -t ${{ matrix.tauri-target }}
       ELECTRON_BUILD_COMMAND: npm run electron-pack
@@ -113,8 +111,9 @@ jobs:
 
       - name: Inject release version
         run: |
-          echo "RELEASE_VERSION=${{ env.RELEASE_VERSION }}" >> $GITHUB_ENV
-          echo "The release version is ${{ env.RELEASE_VERSION }}$"
+          release_version=${GITHUB_REF#refs/*/}
+          echo "RELEASE_VERSION=$release_version" >> $GITHUB_ENV
+          echo "The release version is $release_version"
 
       - name: Authenticate to Google Cloud Platform
         uses: google-github-actions/auth@v1
@@ -126,28 +125,28 @@ jobs:
       - name: Set up Google Cloud SDK
         uses: 'google-github-actions/setup-gcloud@v1'
 
-          #      - name: Clone private maps
-          #        if: ${{ env.IS_PUBLIC != 'YES' }}
-          #        uses: actions/checkout@v3
-          #        with:
-          #          repository: battlecode/private-maps
-          #          token: ${{ secrets.CI_REPOSITORY_CLONE_PAT }}
-          #          path: private-maps
-          #
-          #      - name: Inject private maps
-          #        if: ${{ env.IS_PUBLIC != 'YES' }}
-          #        run: |
-          #          source="private-maps/$RELEASE_ARTIFACT_ID"
-          #          dest="engine/src/main/battlecode/world/resources"
-          #          if [ -d "$source" ]; then
-          #            cp -r -i "$source/." "$dest/" < /dev/null &> private-maps-copy-log
-          #            if [ -s "private-maps-copy-log" ]; then
-          #              echo "FAILED! Public and private maps should not intersect."
-          #              cat private-maps-copy-log
-          #              exit 1
-          #            fi
-          #          fi
-          #
+      - name: Clone private maps
+        if: ${{ env.IS_PUBLIC != 'YES' }}
+        uses: actions/checkout@v3
+        with:
+          repository: battlecode/private-maps
+          token: ${{ secrets.CI_REPOSITORY_CLONE_PAT }}
+          path: private-maps
+      
+      - name: Inject private maps
+        if: ${{ env.IS_PUBLIC != 'YES' }}
+        run: |
+          source="private-maps/$RELEASE_ARTIFACT_ID"
+          dest="engine/src/main/battlecode/world/resources"
+          if [ -d "$source" ]; then
+            cp -r -i "$source/." "$dest/" < /dev/null &> private-maps-copy-log
+            if [ -s "private-maps-copy-log" ]; then
+              echo "FAILED! Public and private maps should not intersect."
+              cat private-maps-copy-log
+              exit 1
+            fi
+          fi
+          
       - name: Set up JDK 8
         uses: actions/setup-java@v3
         with:
@@ -159,11 +158,13 @@ jobs:
         with:
           path: ./client/artifacts
 
-            #- name: Cleanup client artifacts
-            #uses: geekyeggo/delete-artifact@54ab544f12cdb7b71613a16a2b5a37a9ade990af
-            #if: always() # Always cleanup even if other commands failed
-            #with:
-            #name: client-*
+      # Always cleanup even if other commands failed so we don't unnecessarily store
+      # the artifacts in the cloud 
+      - name: Cleanup client artifacts
+        uses: geekyeggo/delete-artifact@54ab544f12cdb7b71613a16a2b5a37a9ade990af
+        if: always()
+        with:
+          name: client-*
 
       - name: Publish to local repository
         run: ./gradlew publishToMavenLocal -Prelease_version=$RELEASE_VERSION
@@ -185,7 +186,7 @@ jobs:
       - name: Upload specs
         run: gsutil -m rsync -a $OBJECT_ACL -r ./specs gs://$GCS_BUCKET/specs/$RELEASE_ARTIFACT_ID/$RELEASE_VERSION
 
-          #      - name: Upload web client
-          #        run: |
-          #          gsutil -m rsync -r -a $OBJECT_ACL dist gs://$GCS_BUCKET/client/$RELEASE_ARTIFACT_ID/$RELEASE_VERSION
-          #        working-directory: ./client
+      - name: Upload web client
+        run: |
+          gsutil -m rsync -r -a $OBJECT_ACL ./artifacts/client-dist gs://$GCS_BUCKET/client/$RELEASE_ARTIFACT_ID/$RELEASE_VERSION
+        working-directory: ./client
