Workflow tauri refactor testing

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -17,12 +17,59 @@ env:
   IS_PUBLIC: NO
 
 jobs:
-  release:
-    name: Release
-    runs-on: ubuntu-latest
+  # TODO: perform all client releases in here
+  # TODO: tauri exclude dmg?
+  release-tauri:
+    name: Tauri Release
     permissions:
       contents: read
       id-token: write
+    strategy:
+      matrix:
+        include:
+          - platform-name: "macos-latest"
+            tauri-name: "macos"
+         # - platform-name: "ubuntu-latest"
+         #    tauri-name: "deb"
+         # - platform-name: "windows-latest"
+         #    tauri-name: "windows"
+    runs-on: ${{ matrix.platform-name }}
+
+    steps:
+      - name: Checkout branch
+        uses: actions/checkout@v3
+
+      - name: Set up Node 16
+        uses: actions/setup-node@v3
+        with:
+          node-version: 16
+
+      - name: Install schema
+        run: npm install
+        working-directory: ./schema
+
+      - name: Install client
+        run: npm install
+        working-directory: ./client
+
+      - name: Build client
+        run: npm run tauri-build
+        working-directory: ./client
+      
+      - name: Upload client artifact
+        uses: actions/upload-artifact@v3
+        with:
+          name: client-${{ matrix.tauri-name }}
+          path: ./client/src-tauri/target/release/bundle/${{ matrix.tauri-name }}
+
+  release-primary:
+    name: Primary Release
+    runs-on: ubuntu-latest
+    needs: release-tauri
+    permissions:
+      contents: read
+      id-token: write
+      actions: write # To cleanup artifacts
 
     steps:
       - name: Checkout branch
@@ -44,54 +91,72 @@ jobs:
       - name: Set up Google Cloud SDK
         uses: 'google-github-actions/setup-gcloud@v1'
 
-      - name: Clone private maps
-        if: ${{ env.IS_PUBLIC != 'YES' }}
-        uses: actions/checkout@v3
-        with:
-          repository: battlecode/private-maps
-          token: ${{ secrets.CI_REPOSITORY_CLONE_PAT }}
-          path: private-maps
+          #      - name: Clone private maps
+          #        if: ${{ env.IS_PUBLIC != 'YES' }}
+          #        uses: actions/checkout@v3
+          #        with:
+          #          repository: battlecode/private-maps
+          #          token: ${{ secrets.CI_REPOSITORY_CLONE_PAT }}
+          #          path: private-maps
+          #
+          #      - name: Inject private maps
+          #        if: ${{ env.IS_PUBLIC != 'YES' }}
+          #        run: |
+          #          source="private-maps/$RELEASE_ARTIFACT_ID"
+          #          dest="engine/src/main/battlecode/world/resources"
+          #          if [ -d "$source" ]; then
+          #            cp -r -i "$source/." "$dest/" < /dev/null &> private-maps-copy-log
+          #            if [ -s "private-maps-copy-log" ]; then
+          #              echo "FAILED! Public and private maps should not intersect."
+          #              cat private-maps-copy-log
+          #              exit 1
+          #            fi
+          #          fi
+          #
+          #      - name: Set up Wine  # See actions/runner-images#743
+          #        run: |
+          #          sudo dpkg --add-architecture i386
+          #          wget -qO - https://dl.winehq.org/wine-builds/winehq.key | sudo apt-key add -
+          #          sudo add-apt-repository ppa:cybermax-dexter/sdl2-backport
+          #          sudo apt-add-repository "deb https://dl.winehq.org/wine-builds/ubuntu $(lsb_release -cs) main"
+          #          sudo apt install --install-recommends winehq-stable
+          #
+          #      - name: Set up JDK 8
+          #        uses: actions/setup-java@v3
+          #        with:
+          #          java-version: 8
+          #          distribution: adopt
+          #
+          #      - name: Set up Node 16
+          #        uses: actions/setup-node@v3
+          #        with:
+          #          node-version: 16
+          #
+          #      - name: Install schema
+          #        run: npm install
+          #        working-directory: ./schema
+          #
+          #      - name: Install client
+          #        run: npm install
+          #        working-directory: ./client
 
-      - name: Inject private maps
-        if: ${{ env.IS_PUBLIC != 'YES' }}
+      - name: Download all tauri artifacts
+        uses: actions/download-artifact@v3
+        with:
+          path: ./client/packaged-tauri
+
+      - name: Cleanup tauri artifacts
+        uses: geekyeggo/delete-artifact@54ab544f12cdb7b71613a16a2b5a37a9ade990af
+        with:
+          token: ${{ secrets.GITHUB_TOKEN }}
+          name: client-*
+
+      - name: Zip tauri artifacts
+        working-directory: ./client/packaged-tauri
         run: |
-          source="private-maps/$RELEASE_ARTIFACT_ID"
-          dest="engine/src/main/battlecode/world/resources"
-          if [ -d "$source" ]; then
-            cp -r -i "$source/." "$dest/" < /dev/null &> private-maps-copy-log
-            if [ -s "private-maps-copy-log" ]; then
-              echo "FAILED! Public and private maps should not intersect."
-              cat private-maps-copy-log
-              exit 1
-            fi
-          fi
-
-      - name: Set up Wine  # See actions/runner-images#743
-        run: |
-          sudo dpkg --add-architecture i386
-          wget -qO - https://dl.winehq.org/wine-builds/winehq.key | sudo apt-key add -
-          sudo add-apt-repository ppa:cybermax-dexter/sdl2-backport
-          sudo apt-add-repository "deb https://dl.winehq.org/wine-builds/ubuntu $(lsb_release -cs) main"
-          sudo apt install --install-recommends winehq-stable
-
-      - name: Set up JDK 8
-        uses: actions/setup-java@v3
-        with:
-          java-version: 8
-          distribution: adopt
-
-      - name: Set up Node 16
-        uses: actions/setup-node@v3
-        with:
-          node-version: 16
-
-      - name: Install schema
-        run: npm install
-        working-directory: ./schema
-
-      - name: Install client
-        run: npm install
-        working-directory: ./client
+          zip -qqr mac-x64.zip macos
+          #zip -qqr linux-x64.zip deb
+          #zip -qqr win-x64.zip windows
 
       - name: Publish to local repository
         run: ./gradlew publishToMavenLocal -Prelease_version=$RELEASE_VERSION
@@ -113,7 +178,7 @@ jobs:
       - name: Upload specs
         run: gsutil -m rsync -a $OBJECT_ACL -r ./specs gs://$GCS_BUCKET/specs/$RELEASE_ARTIFACT_ID/$RELEASE_VERSION
 
-      - name: Upload web client
-        run: |
-          gsutil -m rsync -r -a $OBJECT_ACL dist gs://$GCS_BUCKET/client/$RELEASE_ARTIFACT_ID/$RELEASE_VERSION
-        working-directory: ./client
+          #      - name: Upload web client
+          #        run: |
+          #          gsutil -m rsync -r -a $OBJECT_ACL dist gs://$GCS_BUCKET/client/$RELEASE_ARTIFACT_ID/$RELEASE_VERSION
+          #        working-directory: ./client
